FROM cypress/included:15.9.0
WORKDIR /e2e
# Copy dependency files
COPY package.json package-lock.json ./
RUN npm install
# Copy the rest of your project
COPY . .
# The default command to run when the container starts
CMD ["npm", "test"]
